const postList = [
      {
            postId: 'ocrp1',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 10,
            postOfUser: 'j12',
      },
      {
            postId: 'ocrp2',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',

],
            likes : 8,
            postOfUser: 'z12',
      },
      {
            postId: 'ocrp3',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 8,
            postOfUser: 'c12',
      },
      {
            postId: 'ocrp4',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 2,
            postOfUser: 't12',
      },
      {
            postId: 'ocrp5',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 25,
            postOfUser: 'f12',
      },
      {
            postId: 'ocrp6',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 8,
            postOfUser: 'v12',
      },
      {
            postId: 'ocrp7',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 9,
            postOfUser: 'z12',
      },
      {
            postId: 'ocrp8',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 16,
            postOfUser: 'j12',
      },
      {
            postId: 'ocrp9',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 23,
            postOfUser: 'f12',
      },
      {
            postId: 'ocrp10',
            post: ' A atque velit qui magni officiis in molestiae accusamus sed possimus fuga 33 velit quas ea eius laudantium. Sed sint animi et excepturi voluptatum ab voluptas iusto ad omnis omnis sed esse enim ut quia accusamus ad unde quae Et fuga totam vel molestiae praesentium et cumque dicta eos molestiae adipisci. Sed fugiat vitae ut laudantium optio sit dignissimos deleniti ut alias officia ut reprehenderit nulla aut inventore rerum',
            comments : ['Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
      'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.',
'Lorem ipsum dolor sit amet. Et tenetur voluptate non fuga molestiae cum enim veritatis nam quia aliquam! Eos labore amet est omnis atque id dolorem molestias ut amet perspiciatis non perferendis necessitatibus.'],
            likes : 13,
            postOfUser: 'c12',
      },
]

export default postList;